import { blog1, blog2, blog3 } from '../assets/img';

import { v4 as uuidv4 } from 'uuid';

const blogs = [
  {
    id: uuidv4(),
    img: blog1,
    date: '01 May 22',
    author: 'admin',
    title: 'Handmade Pieces That Took Time To Make',
    body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis assumenda ad beatae itaque totam pariatur repudiandae cupiditate corporis officiis vitae dolor esse perspiciatis, expedita ipsum quibusdam quis, asperiores, hic alias adipisci minus! Recusandae nam corrupti rerum natus voluptatibus ea facere animi laudantium minus! Ea quos nobis ipsam explicabo accusamus. Quam dolor rem hic, repellendus, expedita obcaecati quas ratione itaque architecto vel culpa molestiae perferendis aliquid doloribus esse, sed quasi corrupti dolorem iusto optio. Ex quis placeat magnam possimus blanditiis tempore eveniet corrupti natus perferendis omnis! Assumenda expedita perspiciatis ipsum maxime. Omnis alias esse maiores illum corrupti ea libero animi adipisci sit dicta, ex cum tenetur ipsum quisquam recusandae aperiam nemo, nostrum distinctio perspiciatis commodi autem. Inventore distinctio laboriosam sunt possimus nemo recusandae voluptatem cumque ad consectetur reiciendis laudantium debitis ratione, saepe qui, necessitatibus maiores incidunt fuga numquam excepturi earum quia? Vel neque, nesciunt quo vitae dolorem dignissimos, et, laudantium dicta harum inventore nihil ducimus doloremque nostrum voluptas commodi voluptates exercitationem? Amet quo saepe nulla possimus, blanditiis nemo maiores ut consequatur! Earum facere a accusantium exercitationem deleniti, minima porro totam maiores harum, nulla distinctio molestiae aut laudantium! Odit inventore illo doloremque magni, voluptates facere culpa tenetur. Blanditiis reprehenderit veritatis, quas in laudantium magni eos. Id aspernatur, quidem fuga, veniam eligendi iste, corrupti earum sit ab harum laudantium dicta veritatis quae accusantium? Id nulla nemo porro, perspiciatis fugiat sequi? Accusantium aut labore at pariatur, omnis eveniet exercitationem molestiae, molestias dolores autem et dolorum cupiditate excepturi perspiciatis eligendi debitis, maiores ipsum maxime nesciunt error tempore! Ut nisi unde delectus cupiditate neque porro similique quod tempore exercitationem maiores illo, ipsum rerum? Illum laudantium explicabo maxime molestias vitae dolor possimus, quam quibusdam nihil nesciunt vero aperiam iure quisquam est fugit minima? Iure qui doloribus magnam nesciunt officiis? Suscipit illum autem fugiat deleniti aut atque tenetur!',
  },
  {
    id: uuidv4(),
    img: blog2,
    date: '01 May 22',
    author: 'admin',
    title: 'Handmade Pieces That Took Time To Make',
    body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis assumenda ad beatae itaque totam pariatur repudiandae cupiditate corporis officiis vitae dolor esse perspiciatis, expedita ipsum quibusdam quis, asperiores, hic alias adipisci minus! Recusandae nam corrupti rerum natus voluptatibus ea facere animi laudantium minus! Ea quos nobis ipsam explicabo accusamus. Quam dolor rem hic, repellendus, expedita obcaecati quas ratione itaque architecto vel culpa molestiae perferendis aliquid doloribus esse, sed quasi corrupti dolorem iusto optio. Ex quis placeat magnam possimus blanditiis tempore eveniet corrupti natus perferendis omnis! Assumenda expedita perspiciatis ipsum maxime. Omnis alias esse maiores illum corrupti ea libero animi adipisci sit dicta, ex cum tenetur ipsum quisquam recusandae aperiam nemo, nostrum distinctio perspiciatis commodi autem. Inventore distinctio laboriosam sunt possimus nemo recusandae voluptatem cumque ad consectetur reiciendis laudantium debitis ratione, saepe qui, necessitatibus maiores incidunt fuga numquam excepturi earum quia? Vel neque, nesciunt quo vitae dolorem dignissimos, et, laudantium dicta harum inventore nihil ducimus doloremque nostrum voluptas commodi voluptates exercitationem? Amet quo saepe nulla possimus, blanditiis nemo maiores ut consequatur! Earum facere a accusantium exercitationem deleniti, minima porro totam maiores harum, nulla distinctio molestiae aut laudantium! Odit inventore illo doloremque magni, voluptates facere culpa tenetur. Blanditiis reprehenderit veritatis, quas in laudantium magni eos. Id aspernatur, quidem fuga, veniam eligendi iste, corrupti earum sit ab harum laudantium dicta veritatis quae accusantium? Id nulla nemo porro, perspiciatis fugiat sequi? Accusantium aut labore at pariatur, omnis eveniet exercitationem molestiae, molestias dolores autem et dolorum cupiditate excepturi perspiciatis eligendi debitis, maiores ipsum maxime nesciunt error tempore! Ut nisi unde delectus cupiditate neque porro similique quod tempore exercitationem maiores illo, ipsum rerum? Illum laudantium explicabo maxime molestias vitae dolor possimus, quam quibusdam nihil nesciunt vero aperiam iure quisquam est fugit minima? Iure qui doloribus magnam nesciunt officiis? Suscipit illum autem fugiat deleniti aut atque tenetur!',
  },
  {
    id: uuidv4(),
    img: blog3,
    date: '01 May 22',
    author: 'admin',
    title: 'Handmade Pieces That Took Time To Make',
    body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis assumenda ad beatae itaque totam pariatur repudiandae cupiditate corporis officiis vitae dolor esse perspiciatis, expedita ipsum quibusdam quis, asperiores, hic alias adipisci minus! Recusandae nam corrupti rerum natus voluptatibus ea facere animi laudantium minus! Ea quos nobis ipsam explicabo accusamus. Quam dolor rem hic, repellendus, expedita obcaecati quas ratione itaque architecto vel culpa molestiae perferendis aliquid doloribus esse, sed quasi corrupti dolorem iusto optio. Ex quis placeat magnam possimus blanditiis tempore eveniet corrupti natus perferendis omnis! Assumenda expedita perspiciatis ipsum maxime. Omnis alias esse maiores illum corrupti ea libero animi adipisci sit dicta, ex cum tenetur ipsum quisquam recusandae aperiam nemo, nostrum distinctio perspiciatis commodi autem. Inventore distinctio laboriosam sunt possimus nemo recusandae voluptatem cumque ad consectetur reiciendis laudantium debitis ratione, saepe qui, necessitatibus maiores incidunt fuga numquam excepturi earum quia? Vel neque, nesciunt quo vitae dolorem dignissimos, et, laudantium dicta harum inventore nihil ducimus doloremque nostrum voluptas commodi voluptates exercitationem? Amet quo saepe nulla possimus, blanditiis nemo maiores ut consequatur! Earum facere a accusantium exercitationem deleniti, minima porro totam maiores harum, nulla distinctio molestiae aut laudantium! Odit inventore illo doloremque magni, voluptates facere culpa tenetur. Blanditiis reprehenderit veritatis, quas in laudantium magni eos. Id aspernatur, quidem fuga, veniam eligendi iste, corrupti earum sit ab harum laudantium dicta veritatis quae accusantium? Id nulla nemo porro, perspiciatis fugiat sequi? Accusantium aut labore at pariatur, omnis eveniet exercitationem molestiae, molestias dolores autem et dolorum cupiditate excepturi perspiciatis eligendi debitis, maiores ipsum maxime nesciunt error tempore! Ut nisi unde delectus cupiditate neque porro similique quod tempore exercitationem maiores illo, ipsum rerum? Illum laudantium explicabo maxime molestias vitae dolor possimus, quam quibusdam nihil nesciunt vero aperiam iure quisquam est fugit minima? Iure qui doloribus magnam nesciunt officiis? Suscipit illum autem fugiat deleniti aut atque tenetur!',
  },
  {
    id: uuidv4(),
    img: blog1,
    date: '01 May 22',
    author: 'admin',
    title: 'Handmade Pieces That Took Time To Make',
    body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis assumenda ad beatae itaque totam pariatur repudiandae cupiditate corporis officiis vitae dolor esse perspiciatis, expedita ipsum quibusdam quis, asperiores, hic alias adipisci minus! Recusandae nam corrupti rerum natus voluptatibus ea facere animi laudantium minus! Ea quos nobis ipsam explicabo accusamus. Quam dolor rem hic, repellendus, expedita obcaecati quas ratione itaque architecto vel culpa molestiae perferendis aliquid doloribus esse, sed quasi corrupti dolorem iusto optio. Ex quis placeat magnam possimus blanditiis tempore eveniet corrupti natus perferendis omnis! Assumenda expedita perspiciatis ipsum maxime. Omnis alias esse maiores illum corrupti ea libero animi adipisci sit dicta, ex cum tenetur ipsum quisquam recusandae aperiam nemo, nostrum distinctio perspiciatis commodi autem. Inventore distinctio laboriosam sunt possimus nemo recusandae voluptatem cumque ad consectetur reiciendis laudantium debitis ratione, saepe qui, necessitatibus maiores incidunt fuga numquam excepturi earum quia? Vel neque, nesciunt quo vitae dolorem dignissimos, et, laudantium dicta harum inventore nihil ducimus doloremque nostrum voluptas commodi voluptates exercitationem? Amet quo saepe nulla possimus, blanditiis nemo maiores ut consequatur! Earum facere a accusantium exercitationem deleniti, minima porro totam maiores harum, nulla distinctio molestiae aut laudantium! Odit inventore illo doloremque magni, voluptates facere culpa tenetur. Blanditiis reprehenderit veritatis, quas in laudantium magni eos. Id aspernatur, quidem fuga, veniam eligendi iste, corrupti earum sit ab harum laudantium dicta veritatis quae accusantium? Id nulla nemo porro, perspiciatis fugiat sequi? Accusantium aut labore at pariatur, omnis eveniet exercitationem molestiae, molestias dolores autem et dolorum cupiditate excepturi perspiciatis eligendi debitis, maiores ipsum maxime nesciunt error tempore! Ut nisi unde delectus cupiditate neque porro similique quod tempore exercitationem maiores illo, ipsum rerum? Illum laudantium explicabo maxime molestias vitae dolor possimus, quam quibusdam nihil nesciunt vero aperiam iure quisquam est fugit minima? Iure qui doloribus magnam nesciunt officiis? Suscipit illum autem fugiat deleniti aut atque tenetur!',
  },
  {
    id: uuidv4(),
    img: blog2,
    date: '01 May 22',
    author: 'admin',
    title: 'Handmade Pieces That Took Time To Make',
    body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis assumenda ad beatae itaque totam pariatur repudiandae cupiditate corporis officiis vitae dolor esse perspiciatis, expedita ipsum quibusdam quis, asperiores, hic alias adipisci minus! Recusandae nam corrupti rerum natus voluptatibus ea facere animi laudantium minus! Ea quos nobis ipsam explicabo accusamus. Quam dolor rem hic, repellendus, expedita obcaecati quas ratione itaque architecto vel culpa molestiae perferendis aliquid doloribus esse, sed quasi corrupti dolorem iusto optio. Ex quis placeat magnam possimus blanditiis tempore eveniet corrupti natus perferendis omnis! Assumenda expedita perspiciatis ipsum maxime. Omnis alias esse maiores illum corrupti ea libero animi adipisci sit dicta, ex cum tenetur ipsum quisquam recusandae aperiam nemo, nostrum distinctio perspiciatis commodi autem. Inventore distinctio laboriosam sunt possimus nemo recusandae voluptatem cumque ad consectetur reiciendis laudantium debitis ratione, saepe qui, necessitatibus maiores incidunt fuga numquam excepturi earum quia? Vel neque, nesciunt quo vitae dolorem dignissimos, et, laudantium dicta harum inventore nihil ducimus doloremque nostrum voluptas commodi voluptates exercitationem? Amet quo saepe nulla possimus, blanditiis nemo maiores ut consequatur! Earum facere a accusantium exercitationem deleniti, minima porro totam maiores harum, nulla distinctio molestiae aut laudantium! Odit inventore illo doloremque magni, voluptates facere culpa tenetur. Blanditiis reprehenderit veritatis, quas in laudantium magni eos. Id aspernatur, quidem fuga, veniam eligendi iste, corrupti earum sit ab harum laudantium dicta veritatis quae accusantium? Id nulla nemo porro, perspiciatis fugiat sequi? Accusantium aut labore at pariatur, omnis eveniet exercitationem molestiae, molestias dolores autem et dolorum cupiditate excepturi perspiciatis eligendi debitis, maiores ipsum maxime nesciunt error tempore! Ut nisi unde delectus cupiditate neque porro similique quod tempore exercitationem maiores illo, ipsum rerum? Illum laudantium explicabo maxime molestias vitae dolor possimus, quam quibusdam nihil nesciunt vero aperiam iure quisquam est fugit minima? Iure qui doloribus magnam nesciunt officiis? Suscipit illum autem fugiat deleniti aut atque tenetur!',
  },
];

export default blogs;
